services:
  postgres:
    image: postgres:16
    container_name: choreocreator_postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-940777}
      POSTGRES_DB: choreocreatordb
      PGDATA: /var/lib/postgresql/data/pgdata

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d choreocreatordb"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
